[[plantuml[
@startuml

(Trash) --> (User) : HAS_USER
(Trash) --> (Volume) : HAS_DIMENSIONS
(Trash) --> (Type) : HAS_TYPE
(Trash) --> (Temporary Trash Collector) : HAS_BEEN_PLACED_IN
(Trash) --> (Not foreseen Trash Collector) : HAS_BEEN_PLACEC_IN
(Not foreseen Trash Collector) --> (Location) : HAS_LOCATION
(Not foreseen Trash Collector) --> (Status): HAS_STATUS 
(Not foreseen Trash Collector) --> (Temporary Trash Collector): TO_BE_REPLACED_IN
(Temporary Trash Collector) --> (Location) : HAS_LOCATION
(Temporary Trash Collector) --> (Status): HAS_STATUS 
(Temporary Trash Collector) --> (Definitive Trash Collector): TO_BE_REPLACED_IN
(Definitive Trash Collector) --> (Location) : HAS_LOCATION
(Definitive Trash Collector) --> (Status): HAS_STATUS 

@enduml
]]]